Django/rpsgame/History/urls.py
from django.urls import path
from . import views
app_name="History"
urlpatterns=[
    path("",views.history,name="history")
]

Django/rpsgame/accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns=[
    path('signin_section/',views.signin_section,name='signin_section'),
    path('signin_view/',views.signin_view, name='signin_view'),
    path('login_section/',views.login_section, name='login_section'),
    path('login_view/', views.login_view , name='login_view'),
    path('logout/',views.logout_view , name='logout_view')
]

Django/rpsgame/game/urls.py
from django.urls import path
from . import views
app_name='game'
urlpatterns=[
    path('menu/', views.menu , name='menu'),
    path('gamesec/',views.gameview , name='gameview'),
    path('results/', views.results , name='results'),
]

Django/rpsgame/rpsgame/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('game/',include('game.urls')),
    path('History/' , include('History.urls'))
]

Django/rpsgame/History/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class history(models.Model):
    user=models.OneToOneField(User , on_delete=models.CASCADE)
    winrate=models.FloatField(max_length=3, default=0)
    historyarr=models.CharField(max_length=100 , default="")
    def __str__(self) :
        return self.historyarr

Django/rpsgame/accounts/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

Django/rpsgame/game/models.py
from django.db import models

# Create your models here.
class GameARR(models.Model):
    choice_text=models.CharField(max_length=10)
    def __str__(self):
        return self.choice_text

Django/rpsgame/History/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def history(request):
    sum=0
    counter=0
    arr=[]
    current_user=request.user.history
    if current_user.historyarr:
        for i in current_user.historyarr:
            if i=="1":
                sum+=100
            elif i=="0":
                sum+=0
            counter+=1
            arr.append(i)
        avg=sum/counter
        current_user.winrate=avg
        return HttpResponse(f"{current_user.winrate}<br> {arr} ")
    else:
        return HttpResponse("There is no history")

Django/rpsgame/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import User
from History.models import history


# Create your views here.
def signin_section(request):
    return render(request, "accounts/signin.html")


def signin_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    confirm_password = request.POST["confirm_password"]
    email = request.POST["email"]
    if password == confirm_password:
        u = User.objects.create_user(username=username, password=password, email=email)
        u.save()
        history.objects.create(user=u)
        return HttpResponseRedirect(reverse("accounts:login_section"))
    else:
        password_incorrect = "Password doesn't match"
        return render(
            request, "accounts/signin.html", {"password_incorrect": password_incorrect}
        )


def login_section(request):
    return render(request, "accounts/login.html")


def login_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("game:menu"))
    else:
        login_failed = "Login failed, please try again"
        return render(request, "accounts/login.html", {"login_failed": login_failed})


def logout_view(request):
    logout(request)
    return HttpResponse("SUCCES")

Django/rpsgame/game/views.py
import random as rn
from django.shortcuts import render , get_object_or_404 
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse
from .models import GameARR
from django.contrib.auth.models import User
from django.contrib.auth import  authenticate , login , logout
from django.contrib.auth.decorators import login_required 
# Create your views here.
def menu(request):
    return render(request,'game/menu.html')

@login_required(login_url='/accounts/login_section')
def gameview(request):
    GA=GameARR.objects.all()
    return render(request , 'game/gameview.html' , {"GA":GA} )
def results(request):
    choice=(GameARR.objects.get(pk=request.POST['choice'])).choice_text
    computer=(GameARR.objects.get(pk=rn.randint(1,3))).choice_text
    def gamefunc(arg1,arg2):
        if arg1 == arg2:
            return 2
        elif arg1=='ROCK' and arg2=='SCISSORS':
            return 1
        elif arg1=='ROCK' and arg2=='PAPER':
            return 0    
        elif arg1=='SCISSORS' and arg2=='PAPER':
            return 1
        else :
            return not(gamefunc(arg2,arg1))
    result_game=gamefunc(choice,computer)
    if result_game==1:
        current_user=request.user.history
        current_user.historyarr = current_user.historyarr + "1"
        current_user.save()
        print(current_user.historyarr)
        result_game="You Won"
    elif result_game==0:
        current_user=request.user.history
        current_user.historyarr= current_user.historyarr + "0"
        current_user.save()

        print(current_user.historyarr)
        result_game="You Lose"
    else:
        current_user=request.user.history
        current_user.historyarr= current_user.historyarr + "2"
        current_user.save()
        print(current_user.historyarr)
        result_game="You Tie"

    return render (request , 'game/results.html',{"res_game":result_game})

Django/rpsgame/accounts/templates/accounts/login.html
<form action="{% url 'accounts:login_view' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>verify</h1></legend>
        <b>username:</b><input type="text" name="username"><br><br>
        <b>password:</b><input type="password" name="password">
        {% if login_failed %}
            <p style="color: red;">{{login_failed}}</p>
        {% endif %}
    </fieldset>
    <input type="submit">
</form>
<a href="{% url 'accounts:signin_section' %}">sign in?</a>

Django/rpsgame/accounts/templates/accounts/signin.html
<form action="{% url 'accounts:signin_view' %}" method="post">
    {%csrf_token%}
    <fieldset>
    <legend><h1>signin</h1></legend>
        <b>username:</b><input type="text" name="username" style="margin-left: 55px;"><br>
        <b>password:</b><input type="password" name="password" style="margin-left: 57px ;"><br>
        <b>confirm password:</b><input type="password" name="confirm_password"><br>
        {% if password_incorrect %}
            <h6 style="color: red;">{{password_incorrect}}</h6>
        {% endif %}
        <b>email:</b><input type="text" name="email" style="margin-left: 85px;">    
    </fieldset>
    <input type="submit">
</form>

Django/rpsgame/game/templates/game/gameview.html
<form action="{%url 'game:results'%}" method="post">
    {%csrf_token%}
    <fieldset>
        <legend>
            <h1>ROCK PAPER SCISSORS?
            </h1>
        </legend>
        {% for choice in GA%}
            <input type="radio" name="choice" id="{choice{forloop.counter}}" value="{{choice.id}}">{{choice.choice_text}}
            <label for="{choice{forloop.counter}}"></label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

Django/rpsgame/game/templates/game/menu.html
<ul>
    <li><a href="{% url 'game:gameview'%}">1.Play game</a></li>
    <li><a href="{% url 'History:history'%}">2.History</a></li>
    <li><a href="{% url 'accounts:logout_view'%}">3.Log out</a></li>
</ul>
<a href="{% url 'game:menu'%}"></a>

Django/rpsgame/game/templates/game/results.html
<h1>Results:</h1>
<h2>{{res_game}}</h2>
<a href="{% url 'game:gameview'%}">again?</a>